### PR TITLE
Cleanup emails

### PR DESCRIPTION
**Pull request by mahendra**
* Remove passing checks
* Make emails more beautiful?

@elainearbaugh dunno how this will look

### CODE REVIEW

**Comment by mahendra** [comment]
doing this just because you and @EvanKuhn-Affirm made fun of my code 👼

**Comment by mahendra** [comment]
:-(

**Review by elainearbaugh — APPROVED** [review]
Sorry I was overwhelmed by all the html but looks good

**Comment by mahendra** [comment]
Oh. I had forgotten about this too. Thank you for the approval. Wondering how to test it now... Will figure out a way and then commit it.

**Pull request closed without merging**
